In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
path = 'D://datasets//major//5552743//' 

In [22]:
data = pd.read_csv(path+'database.csv')
data = data.fillna(data.mean())

In [23]:
data.isnull().sum()

village_name     0
ndvi             0
evi_log          0
evi_mean         0
evi_median       0
infra_density    0
electrified      0
dtype: int64

In [24]:
X = data.iloc[:, 1:-1].values
y = data.iloc[:, -1].values

In [50]:
from sklearn.model_selection import train_test_split





# Linear Regression

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Fitting Simple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)


# Random Forest

In [125]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

from sklearn.ensemble import RandomForestClassifier
from scikitplot.metrics import plot_roc

clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

print(y_test)


[1 0 1 ... 1 1 1]


In [126]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.98


In [127]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("Classification Report")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[ 332    3]
 [  37 1628]]
Classification Report
              precision    recall  f1-score   support

           0       0.90      0.99      0.94       335
           1       1.00      0.98      0.99      1665

    accuracy                           0.98      2000
   macro avg       0.95      0.98      0.97      2000
weighted avg       0.98      0.98      0.98      2000





# Gradient Boosting Algorithm


In [128]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier

In [129]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

state = 12  
test_size = 0.30  
  
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train,  
    test_size=test_size, random_state=state)

lr_list = [0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1]

for learning_rate in lr_list:
    gb_clf = GradientBoostingClassifier(n_estimators=20, learning_rate=learning_rate, max_features=2, max_depth=2, random_state=0)
    gb_clf.fit(X_train, y_train)

    print("Learning rate: ", learning_rate)
    print("Accuracy score (training): {0:.3f}".format(gb_clf.score(X_train, y_train)))
    print("Accuracy score (validation): {0:.3f}".format(gb_clf.score(X_val, y_val)))

Learning rate:  0.05
Accuracy score (training): 0.813
Accuracy score (validation): 0.818
Learning rate:  0.075
Accuracy score (training): 0.842
Accuracy score (validation): 0.843
Learning rate:  0.1
Accuracy score (training): 0.873
Accuracy score (validation): 0.867
Learning rate:  0.25
Accuracy score (training): 0.949
Accuracy score (validation): 0.948
Learning rate:  0.5
Accuracy score (training): 0.974
Accuracy score (validation): 0.968
Learning rate:  0.75
Accuracy score (training): 0.974
Accuracy score (validation): 0.968
Learning rate:  1
Accuracy score (training): 0.973
Accuracy score (validation): 0.963


In [130]:
gb_clf2 = GradientBoostingClassifier(n_estimators=20, learning_rate=0.5, max_features=2, max_depth=2, random_state=0)
gb_clf2.fit(X_train, y_train)
predictions = gb_clf2.predict(X_val)

print("Confusion Matrix:")
print(confusion_matrix(y_val, predictions))

print("Classification Report")
print(classification_report(y_val, predictions))

Confusion Matrix:
[[ 414   23]
 [  54 1909]]
Classification Report
              precision    recall  f1-score   support

           0       0.88      0.95      0.91       437
           1       0.99      0.97      0.98      1963

    accuracy                           0.97      2400
   macro avg       0.94      0.96      0.95      2400
weighted avg       0.97      0.97      0.97      2400




# SVM

In [131]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

from sklearn import svm
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [132]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8325


In [133]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("Classification Report")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[   0  335]
 [   0 1665]]
Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       335
           1       0.83      1.00      0.91      1665

    accuracy                           0.83      2000
   macro avg       0.42      0.50      0.45      2000
weighted avg       0.69      0.83      0.76      2000



C:\Users\UB\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
